name: 'Notify Job Status to Slack'
description: 'Notify a job status to a specific Slack channel.'
inputs:
  job-status:
    description: 'job status'
  slack-bot-token:
    description: 'Bot token used to send messages'
  channel:
    description: 'Channel where messages to be sent'
runs:
  using: 'node14'
  main: 'index.js'
 
