name: vulnerability-scan

on:
  push:
  pull_request:
    - master

jobs:
  security:
    name: snyk-security-check
    runs-on: ubuntu-latest
    defaults:
       run:
         shell: bash

    steps:
      - name: Check out repository
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --sarif-file-output=snyk.sarif
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif
 
